### PR TITLE
CAMEL-12040 - upgrade arquillian-jetty-embedded-9 and add jetty deploy dependency

### PR DESCRIPTION
**Pull request by onders86**

### CODE REVIEW

**Comment by davsclaus** [comment]
Isn't it possible to try to fix this to run with the newer Jetty version as we want to use the same version if possible.

**Comment by onders86** [comment]
will look into..

**Comment by onders86** [comment]
This is the point i could get into. Not sure why classloader fails...
servlet exception

**Comment by onders86** [comment]
tried many things.
as a final step i have upgraded arquillian-jetty-embedded-9 to 1.0.0.CR3.
this time,
`[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.example.cdi.rest.servlet.CdiRestServletTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.916 s <<< FAILURE! - in org.apache.camel.example.cdi.rest.servlet.CdiRestServletTest
[ERROR] org.apache.camel.example.cdi.rest.servlet.CdiRestServletTest  Time elapsed: 0.914 s  <<< ERROR!
java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/deploy/AppProvider
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.deploy.AppProvider
`

**Comment by onders86** [comment]
after upgrading arquillian-jetty-embedded-9 to 1.0.0.CR3 and 
adding 
`
<dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>jetty-deploy</artifactId>
      <version>${jetty9-version}</version>
    </dependency>
`

and with jetty 9.4.6.v20170531 from parent/pom.xml

the issue is still there.
seems like the issue is due to 

arquillian-jetty-embedded-9 JettyEmbeddedContainer's compatibility with jetty.
not sure though..
@astefanutti , could you take a look?

**Comment by astefanutti** [comment]
@onders86 it seems a new dependency on `jetty-deploy` must be added:

```xml
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-deploy</artifactId>
    <version>${jetty9-version}</version>
    <scope>runtime</scope>
</dependency>
```

The missing class has been moved there. I've tested with the additional JAR and it works fine :)

**Comment by onders86** [comment]
thanks.
