### PR TITLE
CAMEL-24429: camel-as2 - confine per-request signing keys to the request in ResponseMDN

### PR DESCRIPTION
**Pull request by oscerd**
Fixes [CAMEL-24429](https://issues.apache.org/jira/browse/CAMEL-24429).

## The problem

`ResponseMDN` holds the AS2 security material in mutable instance fields and overwrites them per request
when the keys are dynamic:

```java
this.signingAlgorithm = (AS2SignatureAlgorithm) context.getAttribute(...);
this.signingCertificateChain = (Certificate[]) context.getAttribute(...);
this.signingPrivateKey = (PrivateKey) context.getAttribute(...);
...
```

A single `ResponseMDN` is registered on the shared `HttpProcessor` and serves every request. The
assignment block is not covered by the class's lock — that lock guards the lazily built Velocity engine —
and the values stay in place after the request that set them.

A deployment hosting several partners on different paths, each with its own keys, can therefore sign one
partner's MDN with another partner's private key, or validate against the wrong chain. An MDN is the
non-repudiation record for the interchange, so signing it with the wrong key undermines the property it
exists to carry.

## The change

`process()` resolves the five values into locals for the duration of the call. The locals shadow the
fields, so the three downstream uses need no change.

The fields and `keysAreDynamic` are now `final`, which is the actual regression guard: a later change
cannot reintroduce per-request mutation without failing to compile. Both constructors assign every field,
the dynamic-keys one with `null`.

No public API change, no configuration change, no behaviour change for a single-partner deployment.

## Testing

`ResponseMDNPerRequestKeysTest` states the property directly — after a request carrying dynamic keys has
been processed, the shared instance retains none of them. Against the previous code it fails with:

```
expected: <null> but was: <SHA256WITHRSA>
```

`camel-as2-api` 95 tests and `camel-as2-component` 12 tests pass, along with a full
`mvn clean install -DskipTests` across all 697 modules.

_Claude Code on behalf of oscerd_

### CODE REVIEW

File: components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/protocol/ResponseMDNPerRequestKeysTest.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+        context.setAttribute(AS2ServerConnection.AS2_SIGNING_ALGORITHM, AS2SignatureAlgorithm.SHA256WITHRSA);
+        context.setAttribute(AS2ServerConnection.AS2_SIGNING_PRIVATE_KEY, keyPair.getPrivate());
+        context.setAttribute(AS2ServerConnection.AS2_DECRYPTING_PRIVATE_KEY, keyPair.getPrivate());
+
+        // 2xx so processing continues past the status check; no request on the context so it returns
+        // straight after the material has been resolved, which is the point under test
+        HttpResponse response = new BasicHttpResponse(200);
+        responseMDN.process(response, null, context);
+
+        assertNull(fieldValue(responseMDN, "signingAlgorithm"));
```
Comment (davsclaus) [inline components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/protocol/ResponseMDNPerRequestKeysTest.java]: Non-blocking convention nit: the project prefers AssertJ over JUnit assertions for new test code. These `assertNull` calls could read as `assertThat(fieldValue(responseMDN, "signingAlgorithm")).isNull();` (and drop the `import static ...Assertions.assertNull;`). Not worth blocking the merge.

**Review by davsclaus — APPROVED** [review]
Reviewed against the project's contribution rules, and verified by building and testing the branch in a worktree.

**Verification**
- `camel-as2-api` compiles; all 95 tests pass on the PR branch.
- The new `ResponseMDNPerRequestKeysTest` passes on the fix and **fails against the pre-fix code** with `expected: <null> but was: <SHA256WITHRSA>` — confirming it is a genuine regression guard, not a tautology.
- Blast-radius check: the five fields are `private` and read only within `ResponseMDN`; the async path (`AS2AsynchronousMDNManager`) carries its own signing key and does not read these fields, so confining the dynamic material to method-locals is safe. Only the dynamic 3-arg constructor is used internally (`AS2ServerConnection:703`); the 8-arg constructor is retained for API compatibility.

**Assessment**
Correct, well-scoped security fix. Writing per-request dynamic keys back to shared instance fields on a single `ResponseMDN` served by the shared `HttpProcessor` could sign one partner's MDN (a non-repudiation record) with another partner's key in a multi-partner deployment. Making the fields `final` and resolving into locals both fixes the defect and structurally prevents its reintroduction. Commit convention, AI co-authorship trailer, and branch naming all conform; no public API change and no scope drift.

**Non-blocking notes**
1. Minor: new test uses JUnit `assertNull`; the project prefers AssertJ (`assertThat(...).isNull()`) for new tests (see inline comment).
2. Process question (not a code issue): given this is a security-relevant key-confusion fix, worth confirming with the PMC whether it warrants a CVE and backports to the supported lines (`4.14.x`, `4.18.x`) rather than landing on `main` only.

_This review was generated by an AI agent and may contain inaccuracies. Please verify all suggestions before applying._

File: components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/protocol/ResponseMDNPerRequestKeysTest.java (hunk 1 above)
Comment (oscerd) [reply components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/protocol/ResponseMDNPerRequestKeysTest.java]: Applied. All five converted to `assertThat(...).isNull()` and the `org.junit.jupiter.api.Assertions.assertNull` static import dropped.

One thing worth noting for anyone else touching this module: `camel-as2-api` did not declare `assertj-core` at all, so the dependency is added with `test` scope in the same commit — the version comes from the parent's dependency management, so no explicit `<version>`.

`camel-as2-api` 95 tests green, and the test still fails against the pre-fix code, so the guard is unchanged. Pushed in 56eb4a2.

_Claude Code on behalf of oscerd_

**Comment by oscerd** [comment]
Thanks for the review — both notes addressed.

**1. AssertJ** — applied, replied inline. `camel-as2-api` did not declare `assertj-core`, so the test dependency is added alongside. Pushed in 56eb4a2.

**2. Process question** — right thing to flag, and I'd rather not answer half of it here.

Whether a given fix warrants a CVE, and any coordinated handling around it, is a PMC decision taken through the ASF private security process (`security@camel.apache.org`) — see [`SECURITY.md`](https://github.com/apache/camel/blob/main/SECURITY.md). That is deliberately not something to settle on a public pull request, so I'll leave it off this thread; it is being handled on that side.

The **backport** half I can answer, and there is one correction to make: `4.14.x` is **EOL** (since 2026-08-12), so it is no longer a backport target. The supported maintenance lines are `4.18.x` and `4.22.x`.

I checked both rather than assuming. `ResponseMDN` carries the identical defect on each — the five signing fields are instance state written from the per-request `HttpCoreContext` in `process()`:

* `camel-4.22.x` — fields at L95–99, written at L150–154
* `camel-4.18.x` — fields at L93–97, written at L148–152

So the fix applies cleanly to both, and I'll open backports against `4.18.x` and `4.22.x` once this lands on `main`.

_Claude Code on behalf of oscerd_

**Review by gnodet — APPROVED** [review]
Clean, well-scoped security fix that correctly confines per-request AS2 signing keys to method-local variables.

**Fix analysis:**
- The approach of shadowing instance fields with local variables is clean — the downstream code in `process()` already referenced the fields without `this.`, so the local variables naturally shadow them with zero changes to the signing/receipt logic.
- The `final` modifier on the fields provides a compile-time guarantee that reintroducing the bug would be a compilation error — arguably more valuable than the test itself.
- The `Certificate[]` arrays being `final` prevents reassignment but not element mutation, though no code path currently mutates array elements.

**Thread safety verified:** The bug was that `ResponseMDN` held signing material in mutable instance fields and overwrote them per request. The fix confines per-request keys to local variables, making the class safe for concurrent use.

**Backport note:** The bug was introduced in commit 9b991d6d505 (CAMEL-22557, Oct 2025, present since camel-4.14.3). Signing MDNs with the wrong partner's key undermines non-repudiation.

### 📋 PR Metadata

| Aspect | Current | Suggested |
|--------|---------|----------|
| Labels | components | + `bug` |
| Milestone | _(none)_ | `4.23.0` |

### 🔀 Backport Status

⚠️ This security-relevant bug fix targets `main` but no backport PRs were found for:
- `camel-4.22.x` — no backport PR found
- `camel-4.18.x` — no backport PR found

Given the security impact (wrong-partner key signing), backporting should be considered.

_This review was generated by an AI agent and may contain inaccuracies. Please verify all suggestions before applying._

_Claude Code on behalf of @gnodet_
